spring:
  profiles:
    active: dev

---
#development environment
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/honey?useUnicode=true&useSSL=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: honey
    password: honey

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


server:
  port: 28080

logging:
  level:
    # 自定义不同类的日志级别
    cn.jiayuli.honey: debug
    root: info
---
#test environment
spring:
  profiles: test
  jpa:
    open-in-view: false

server:
  port: 28085


---
#production environment
spring:
  profiles: prod
  jpa:
    open-in-view: false

server:
  port: 28090

