package cn.jiayuli.springbootcxf.client.local.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2020-03-21T16:35:52.223+08:00
 * Generated source version: 3.2.9
 *
 */
@WebService(targetNamespace = "http://webservice.springbootcxf.jiayuli.cn/", name = "demoWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DemoWebService {

    @WebMethod(action = "sayDemo")
    @RequestWrapper(localName = "sayDemo", targetNamespace = "http://webservice.springbootcxf.jiayuli.cn/", className = "cn.jiayuli.springbootcxf.client.local.demo.SayDemo")
    @ResponseWrapper(localName = "sayDemoResponse", targetNamespace = "http://webservice.springbootcxf.jiayuli.cn/", className = "cn.jiayuli.springbootcxf.client.local.demo.SayDemoResponse")
    @WebResult(name = "sayDemoResponse", targetNamespace = "")
    public java.lang.String sayDemo(
        @WebParam(name = "sayDemoRequest", targetNamespace = "")
        java.lang.String sayDemoRequest
    );
}
