package cn.jiayuli.springbootcxf.client.local.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2020-03-21T16:35:52.230+08:00
 * Generated source version: 3.2.9
 *
 */
@WebServiceClient(name = "demoWebService",
                  wsdlLocation = "http://localhost:38080/cxf/demo?wsdl",
                  targetNamespace = "http://webservice.springbootcxf.jiayuli.cn/")
public class DemoWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.springbootcxf.jiayuli.cn/", "demoWebService");
    public final static QName DemoWebServicePort = new QName("http://webservice.springbootcxf.jiayuli.cn/", "demoWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:38080/cxf/demo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:38080/cxf/demo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DemoWebService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemoWebService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemoWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DemoWebService
     */
    @WebEndpoint(name = "demoWebServicePort")
    public DemoWebService getDemoWebServicePort() {
        return super.getPort(DemoWebServicePort, DemoWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoWebService
     */
    @WebEndpoint(name = "demoWebServicePort")
    public DemoWebService getDemoWebServicePort(WebServiceFeature... features) {
        return super.getPort(DemoWebServicePort, DemoWebService.class, features);
    }

}
