# DataSource Config
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/allsome?useUnicode=true&useSSL=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    username: allsome
#    password: myallsome

# Logger Config
logging:
  level:
    root : info
    cn.jiayuli.wechat: debug

# Server Config
server:
  port: 80

# Wechat Config
wechat:
  #公众号AppID
  appID: wxf5115d32f0a2f3a2
  #公众平台配置的APPSecret
  secret: 3c7dee1a349a6e18bb5569311a647264
  #公众平台配置的Token
  token: token_dev_123
  #公众平台配置的EncodingAESKey
  encodingAESKey: mtSVZ7mKbxhggC1UHgAQSBKPYAwWHGx6T43Ev59x99L